/**
 * Base (English) string resource.
 *
 * This is the source of truth for `TranslationKey`. A translator comment sits
 * above any entry with a placeholder or plural form (MR-13: "translator
 * comments for placeholders"). Nothing here concatenates two keys into a
 * sentence — each entry is a complete, grammatical sentence or label.
 *
 * Copy follows MR-03 "Copy style": concise, respectful, no "failure" language
 * for a disabled setting, no idioms.
 */
export const en = {
  // --- Navigation (MR-03) ----------------------------------------------------
  // Internal route key stays `Today` (`tabRoutes.today`) — only the visible
  // label changed, so navigation state/deep links/tests keyed on the route
  // name are unaffected.
  'nav.today': 'Upcoming',
  'nav.library': 'Library',
  'nav.reminders': 'Reminders',
  'nav.settings': 'Settings',
  'nav.add': 'Add',
  'add.sheetTitle': 'Add',
  'add.importMediaSubtitle': 'Bring a video, audio or image into your library',
  'add.createReminder': 'Create reminder',
  'add.createReminderSubtitle': 'Schedule something from your library',

  // --- Onboarding --------------------------------------------------------------
  'onboarding.purpose.title': 'Make local media useful at the right moment',
  'onboarding.purpose.body':
    'Import videos, audio or images and schedule them as private reminders. Nothing is uploaded.',
  'onboarding.purpose.continue': 'Continue',
  'onboarding.purpose.privacyDetails': 'View privacy details',
  'onboarding.adaptive.title': 'It shows up the way you need it to',
  'onboarding.adaptive.body':
    'When your phone is locked, a reminder can open like an alarm. While you are using your phone, Android shows a compact notification instead.',
  'onboarding.permissions.title': 'Permissions, only when needed',
  'onboarding.permissions.body':
    "You'll be asked for notification and exact-alarm permissions the first time they're actually needed to schedule a reminder — never upfront, and never for anything else.",
  'onboarding.start': 'Start with my library',
  'onboarding.back': 'Back',
  'onboarding.skip': 'Skip',
  // Translator note: {current}/{total} are 1-based page numbers, e.g. "1 of 3".
  'onboarding.pageIndicator': '{current} of {total}',

  // --- Upcoming (formerly "Today" — internal keys/route unchanged, MR-03) ----
  'today.title': 'Upcoming',
  'today.status.ready': 'Ready',
  'today.status.actionNeeded': 'Action needed',
  'today.status.limitedTiming': 'Limited timing',
  'today.empty.title': 'No reminders scheduled',
  'today.empty.body': 'Import something meaningful, then choose when it should return.',
  'today.empty.importMedia': 'Import media',
  'today.empty.createTextCard': 'Create reminder from a text card',
  'today.capability.exactTimingOff.title': 'Exact timing is off',
  'today.capability.exactTimingOff.effect': 'Android may deliver reminders later.',
  'today.capability.openHealth': 'Open Health',
  // Translator note: {count} is a plain integer.
  'today.activeReminderCount': '{count} active reminders',
  'today.nextReminder': 'Next reminder',
  'today.nextReminder.todayAt': 'Today at {time}',
  'today.nextReminder.tomorrowAt': 'Tomorrow at {time}',
  'today.nextReminder.weekdayAt': '{weekday} at {time}',
  'today.playPreview': 'Play',
  'today.edit': 'Edit',
  'today.more': 'More',
  // The date-section heading text itself, not the page title — spec:
  // "Do not rename date-section headings. The first schedule section should
  // still be called TODAY." Rendered visually upper-cased; the base string
  // stays sentence case for screen readers/other locales.
  'today.section.today': 'Today',
  'today.section.tomorrow': 'Tomorrow, {date}',
  'today.section.empty': 'No alarms scheduled',
  'today.previewSoundFor': 'Preview sound for {label} at {time}',

  // --- Library ---------------------------------------------------------------
  'library.title': 'Library',
  'library.search.placeholder': 'Search media',
  'library.filter.videos': 'Videos',
  'library.filter.audio': 'Audio',
  'library.filter.images': 'Images',
  'library.filter.text': 'Text',
  'library.filter.missing': 'Missing',
  'library.filters.more': 'More filters',
  'library.filters.fewer': 'Fewer filters',
  // The two `library.empty.*` states cover different causes: a genuinely
  // empty library (first-run) versus a search/kind/category filter that
  // matched nothing (recoverable — see `library.empty.filtered.*`).
  'library.empty.title': 'Your library is empty',
  'library.empty.body': 'Imported videos, audio, images and text cards appear here.',
  'library.empty.filtered.title': 'No media matches these filters',
  'library.empty.filtered.body': 'Try a different search term, or clear the filters to see everything.',
  'library.empty.filtered.clearFilters': 'Clear filters',
  'library.sort.recentlyAdded': 'Recently added',
  'library.sort.name': 'Name',
  'library.sort.mostScheduled': 'Most scheduled',
  'library.sort.fileSize': 'File size',
  'library.import.copying': 'Copying',
  'library.import.checking': 'Checking',
  'library.import.creatingPreview': 'Creating preview',
  'library.import.ready': 'Ready',
  'library.import.errorUnsupportedType': 'This file type is not supported.',
  'library.import.errorUnreadable':
    'The file could not be read. It may have moved or be damaged.',
  // Translator note: {megabytes} is a localized number, already formatted.
  'library.import.errorInsufficientSpace':
    'Not enough free space. Free at least {megabytes} MB and try again.',
  'library.import.errorCancelled': 'Import was cancelled. No file was added.',
  // Translator note: {count} is a plain integer, always 1 today (imports are one file at a time).
  'library.import.success': '{count} assets imported successfully.',
  // Translator note: {count} is a plain integer.
  'library.grid.itemCount': '{count} items',
  'library.kind.video': 'Video',
  'library.kind.audio': 'Audio',
  'library.kind.image': 'Image',
  'library.kind.text': 'Text',
  'library.integrity.missing': 'Missing',
  'library.detail.addReminder': 'Add reminder',
  'library.detail.playPreview': 'Play preview',
  'library.detail.editDetails': 'Edit details',
  'library.detail.exportItem': 'Export this item',
  'library.detail.notes': 'Notes',
  'library.detail.attachedReminders': 'Attached reminders',
  'library.detail.noAttachedReminders': 'No reminders use this media yet.',
  'library.detail.fileIntegrity': 'File integrity',
  'library.detail.deleteTitle': 'Delete this media?',
  'library.detail.deleteConfirmBody': 'This removes the file from your library.',
  // Translator note: {count} is a plain integer, always 1 or more here.
  'library.detail.deleteDependencyWarning': 'This media is used by {count} reminders.',
  'library.detail.deleteKeepDisabled': 'Keep reminders disabled',
  'library.detail.deleteMediaAndReminders': 'Delete media and reminders',
  'library.detail.notFound.title': 'This media is no longer available',
  'library.detail.notFound.effect': 'It may have been removed from the library.',
  'library.detail.titleLabel': 'Title',
  'library.detail.titlePlaceholder': 'Name this media',
  'library.detail.notesPlaceholder': 'Add a note (optional)',
  'library.detail.renameValidationTitleRequired': 'Title cannot be empty.',
  'library.player.close': 'Close preview',
  'library.player.loadError': "Couldn't play this file.",
  'library.player.play': 'Play {title}',
  'library.detail.emptySelectionTitle': 'Select an item',
  'library.detail.emptySelectionBody': 'Choose something from your library to see its details here.',
  'library.selection.select': 'Select',
  'library.selection.back': 'Exit selection',
  'library.selection.export': 'Export',
  'library.selection.delete': 'Delete',
  // Translator note: {count} is a plain integer, always 1 or more here.
  'library.selection.checkboxLabel': 'Select {title}',
  'library.selection.checkedLabel': 'Selected: {title}',
  'library.selection.emptyWarning': 'Select at least one item, or tap Back to exit.',
  'library.selection.exportSuccess': '{count} assets exported successfully.',
  'library.selection.deleteSuccess': '{count} assets deleted successfully.',
  'library.selection.exportError': "Couldn't export the selected items. Try again.",
  'library.selection.deleteError': "Couldn't delete the selected items. Try again.",
  'library.editAsset.title': 'Edit media asset',
  'library.editAsset.editLabel': 'Edit {title}',
  'library.editAsset.saveSuccess': 'Media details updated successfully.',

  // --- Reminders / editor (MR-03) ------------------------------------------
  'reminders.title': 'Reminders',
  'reminders.list.enableToggle': 'Enable {label}',
  'reminders.list.deleteAction': 'Delete {label}',
  'reminders.editor.what': 'What',
  'reminders.editor.when': 'When',
  'reminders.editor.alertStyle': 'Alert style',
  'reminders.editor.snooze': 'Snooze',
  'reminders.editor.options': 'Options',
  'reminders.editor.preview': 'Preview',
  'reminders.editor.save': 'Save reminder',
  'reminders.editor.change': 'Change',
  // Translator note: {time} and {date} are already locale-formatted.
  'reminders.editor.previewNext': 'Next: {date} at {time}',
  'reminders.repeat.once': 'Once',
  'reminders.repeat.everyDay': 'Every day',
  'reminders.repeat.selectedDays': 'Selected days',
  'reminders.repeat.monthly': 'Monthly',
  'reminders.repeat.yearly': 'Yearly',
  'reminders.repeat.custom': 'Custom',
  'reminders.editor.dayOfMonth': 'Day of month',
  'reminders.editor.month': 'Month',
  'reminders.editor.intervalDays': 'Repeat every',
  // Translator note: {days} is a plain integer, always 1 or more.
  'reminders.editor.intervalDaysValue': 'Every {days} days',
  'reminders.editor.increase': 'Increase',
  'reminders.editor.decrease': 'Decrease',
  'reminders.editor.amPm': 'AM or PM',
  'reminders.editor.hour': 'Hour',
  'reminders.editor.minute': 'Minute',
  // Translator note: {time} is the resolved local time after a DST gap.
  'reminders.dst.gap': '{original} does not occur on this date. The reminder will use {resolved}.',
  'reminders.dst.useSecond': 'Use second {time}',
  'reminders.editor.newTitle': 'New reminder',
  'reminders.editor.editTitle': 'Edit reminder',
  'reminders.editor.createSuccess': 'Reminder created successfully.',
  'reminders.editor.updateSuccess': 'Reminder updated successfully.',
  'reminders.editor.mediaSection': 'Media',
  'reminders.editor.changeMedia': 'Change media',
  'reminders.editor.chooseMedia': 'Choose media',
  'reminders.selectMedia.title': 'Select media',
  'reminders.selectMedia.useThis': 'Use this',
  'reminders.editor.label': 'Label',
  'reminders.editor.labelPlaceholder': 'Name this reminder',
  'reminders.editor.notesPlaceholder': 'Optional notes',
  'reminders.editor.date': 'Date',
  'reminders.editor.time': 'Time',
  'reminders.editor.weekdays': 'Repeat on',
  'reminders.editor.snoozeDefault': 'Default snooze',
  // Translator note: {minutes} is a plain integer.
  'reminders.editor.snoozeMinutes': '{minutes} minutes',
  'reminders.editor.historyToggle': 'Record history',
  'reminders.editor.historyHelper': 'Keep a local record of Play, Snooze and Dismiss for this reminder.',
  'reminders.editor.enabledToggle': 'Enabled',
  'reminders.editor.capabilitySummary': 'Capability summary',
  'reminders.editor.validationLabelRequired': 'Give this reminder a name.',
  'reminders.editor.validationMediaRequired': 'Choose media for this reminder.',
  'reminders.editor.saved': 'Reminder saved',
  'reminders.editor.notificationsBlockedTitle': 'Notifications are turned off',
  'reminders.editor.notificationsBlockedBody':
    "This reminder won't be able to alert you until notifications are enabled for Nudgio.",
  'reminders.editor.notificationsBlockedContinue': 'Save anyway',
  'reminders.editor.notificationsBlockedOpenSettings': 'Open Settings',
  'reminders.detail.title': 'Reminder',
  'reminders.detail.edit': 'Edit',
  'reminders.detail.delete': 'Delete reminder',
  'reminders.detail.deleteConfirmTitle': 'Delete this reminder?',
  'reminders.detail.deleteConfirmBody': 'The media itself is not deleted.',
  'reminders.detail.deleteSuccess': 'Reminder deleted successfully.',
  'reminders.detail.next': 'Next occurrence',
  'reminders.detail.schedule': 'Schedule',
  'reminders.detail.alertStyle': 'Alert style',
  'reminders.detail.snooze': 'Snooze',
  'reminders.detail.disabledNotice': 'This reminder is disabled and will not alert.',
  'reminders.detail.needsSetupNotice': 'This reminder needs a capability fixed before it can alert.',
  'reminders.weekday.mon': 'Mon',
  'reminders.weekday.tue': 'Tue',
  'reminders.weekday.wed': 'Wed',
  'reminders.weekday.thu': 'Thu',
  'reminders.weekday.fri': 'Fri',
  'reminders.weekday.sat': 'Sat',
  'reminders.weekday.sun': 'Sun',
  'reminders.weekday.monday': 'Monday',
  'reminders.weekday.tuesday': 'Tuesday',
  'reminders.weekday.wednesday': 'Wednesday',
  'reminders.weekday.thursday': 'Thursday',
  'reminders.weekday.friday': 'Friday',
  'reminders.weekday.saturday': 'Saturday',
  'reminders.weekday.sunday': 'Sunday',

  // --- Profiles (ADR-018) -----------------------------------------------------
  'profile.gentle.name': 'Gentle',
  'profile.gentle.description': 'Heads-up if Android permits, one short vibration, sound off by default.',
  'profile.standard.name': 'Standard',
  'profile.standard.description': 'Heads-up with sound. Full-screen alarm when your phone is locked.',
  'profile.persistent.name': 'Persistent',
  'profile.persistent.description': 'Repeated alerts and continuous alarm when locked.',
  'profile.persistent.notice': 'Not for emergencies.',

  // --- Due presentation (MR-03) ----------------------------------------------
  'due.play': 'Play',
  'due.snooze': 'Snooze',
  'due.dismiss': 'Dismiss',
  // Translator note: {time} is the resolved absolute time, e.g. "6:25 AM".
  'due.snoozedUntil': 'Snoozed until {time}',
  'due.silenceSound': 'Silence sound',

  // --- Health ------------------------------------------------------------------
  'health.title': 'Health',
  'health.testReminder': 'Test reminder',
  'health.lastSchedulerCheck': 'Last scheduler check',
  'health.oemNote':
    'Your device manufacturer may delay background alerts. Use Test reminder after changing battery settings.',
  'health.action.allow': 'Allow',
  'health.action.openSettings': 'Open settings',
  'health.capability.notifications.title': 'Notifications',
  'health.capability.exact_alarm.title': 'Exact alarm timing',
  'health.capability.battery_environment.title': 'Battery settings',
  'health.capability.scheduler.title': 'Scheduler',
  'health.capability.full_screen_intent.title': 'Full-screen alarms',
  'health.capability.channels.title': 'Notification channels',
  // Native `CapabilityItem.effectKey` values (MR-08). Kept in this exact
  // shape — one key per observed state, plain-language consequence, no
  // "failure" wording for a state the user has not actually done anything
  // wrong to reach (MR-03 "Copy style").
  'capability.notifications.ready': 'Reminders can show a notification.',
  'capability.notifications.blocked': 'Reminders cannot show a notification until this is allowed.',
  'capability.exactAlarm.ready': 'Reminders fire at the exact time you set.',
  'capability.exactAlarm.limited': 'Android may deliver reminders a little later than the exact time you set.',
  'capability.batteryEnvironment.ready': 'Background alerts are not restricted.',
  'capability.batteryEnvironment.limited':
    'Your battery settings may delay background alerts. This is expected — Nudgio never asks to be exempted.',
  'capability.batteryEnvironment.unknown': "This device doesn't report battery-restriction status.",
  'capability.scheduler.ready': 'The next reminder is registered with Android.',

  // --- Backup (MR-03) ----------------------------------------------------------
  'backup.export.title': 'Export',
  'backup.export.privacyWarning':
    'This ZIP contains your media and reminder names. Anyone with the file can open it.',
  'backup.export.chooseDestination': 'Choose where to save',
  'backup.export.share': 'Share',
  'backup.export.done': 'Done',
  'backup.export.mediaCount': 'Media',
  'backup.export.reminderCount': 'Reminders',
  'backup.export.estimatedSize': 'Estimated size',
  'backup.export.exporting': 'Creating archive',
  'backup.export.successTitle': 'Export complete',
  // Translator note: {fileName}, {size} and {hash} are already formatted values.
  'backup.export.successBody': '{fileName} · {size}',
  'backup.export.hash': 'Checksum: {hash}',
  'backup.import.title': 'Import',
  'backup.import.chooseFile': 'Choose backup file',
  'backup.import.inspecting': 'Inspecting backup',
  'backup.import.inspectOnly': 'Inspect only',
  'backup.import.inspectOnlyDescription': 'Look at what is in this backup. Nothing on this device changes.',
  'backup.import.merge': 'Merge',
  'backup.import.mergeDescription': 'Add this backup’s media and reminders alongside what you already have.',
  'backup.import.replace': 'Replace',
  'backup.import.replaceDescription': 'Erase everything on this device first, then restore only what is in this backup.',
  'backup.import.replaceNotice': 'This cannot be undone.',
  'backup.import.replaceConfirmToken': 'REPLACE',
  'backup.import.replaceConfirmTitle': 'Replace all local data?',
  'backup.import.replaceConfirmBody':
    'Everything currently on this device will be replaced with the backup. This can be undone immediately after import, but not later.',
  'backup.import.previewCreatedAt': 'Created',
  'backup.import.previewSourceVersion': 'From app version {version}',
  'backup.import.previewSize': 'Archive size',
  'backup.import.checksumValid': 'Checksum verified',
  'backup.import.checksumInvalid': 'Checksum does not match. This archive may be damaged.',
  'backup.import.compatibilityCompatible': 'Compatible with this app version',
  'backup.import.compatibilityMigratable': 'Will be upgraded during import',
  'backup.import.compatibilityTooNew': 'This backup was created by a newer app version',
  'backup.import.compatibilityUnsupported': 'This backup format is not supported',
  'backup.import.conflictsTitle': 'Conflicts found',
  // Translator note: {count} is a plain integer.
  'backup.conflict.media': '{count} media conflicts',
  'backup.conflict.reminder': '{count} reminder conflicts',
  'backup.conflict.profile': '{count} profile conflicts',
  'backup.conflict.category': '{count} category conflicts',
  'backup.conflict.tag': '{count} tag conflicts',
  'backup.conflict.keptNewer': 'Kept the newer version',
  'backup.conflict.keptExisting': 'Kept what was already on this device',
  'backup.import.committing': 'Restoring',
  'backup.import.successTitle': 'Import complete',
  // Translator note: {mediaCount} and {reminderCount} are plain integers.
  'backup.import.successBody': 'Restored {mediaCount} media items and {reminderCount} reminders.',

  // --- Settings (MR-04, appearance) -------------------------------------------
  'settings.title': 'Settings',
  'settings.appearance.title': 'Appearance',
  'settings.appearance.theme': 'Theme',
  'settings.appearance.theme.system': 'System',
  'settings.appearance.theme.light': 'Light',
  'settings.appearance.theme.dark': 'Dark',
  'settings.appearance.materialYou': 'Use wallpaper colors',
  'settings.appearance.materialYou.helper':
    'Match app colors to your device wallpaper (Android 12 and later).',
  'settings.section.remindersAndAlerts': 'Reminders and alerts',
  'settings.section.dataAndPrivacy': 'Data and privacy',
  'settings.section.support': 'Support',
  'settings.row.health': 'Health',
  'settings.row.health.subtitle': 'Permissions and scheduler status',
  'settings.row.profiles': 'Alert profiles',
  'settings.row.profiles.subtitle': 'Gentle, Standard, Persistent',
  'settings.alarmPreview.hint': 'Tap Preview to see and hear what each alert style looks like.',
  'settings.alarmPreview.notificationTitle': '{name} preview',
  'settings.alarmPreview.scheduled': "Preview scheduled — check your notifications in a few seconds.",
  'settings.row.defaults': 'Reminder defaults',
  'settings.row.defaults.subtitle': 'Default snooze duration',
  'settings.row.statistics': 'Statistics',
  'settings.row.statistics.subtitle': 'Local history of your reminders',
  'settings.row.backup': 'Backup',
  'settings.row.backup.subtitle': 'Export your media and reminders',
  'settings.row.import': 'Import',
  'settings.row.import.subtitle': 'Restore from a backup file',
  'settings.row.accessibility': 'Accessibility',
  'settings.row.accessibility.subtitle': 'Reduced motion, high contrast, haptics',
  'settings.row.privacy': 'Privacy',
  'settings.row.privacy.subtitle': 'What stays on this device',
  'settings.row.about': 'About',
  'settings.row.about.subtitle': 'Version, licenses, source',
  'settings.defaults.snoozeLabel': 'Default snooze duration',
  'settings.accessibility.reduceMotion': 'Reduce motion',
  'settings.accessibility.reduceMotion.helper': 'Follows your system setting; shown here for reference.',
  'settings.accessibility.fontScale': 'Text size follows your system font setting.',
  'settings.accessibility.highContrast': 'High contrast',
  'settings.accessibility.on': 'On',
  'settings.accessibility.off': 'Off',
  'settings.accessibility.strongerHaptics': 'Stronger haptics',
  'settings.accessibility.strongerHaptics.helper':
    'Use a longer vibration for accept, snooze and delete confirmations.',
  'action.preview': 'Preview',
  'settings.privacy.body':
    'Nudgio has no account, no analytics and no Internet permission. Everything stays on this device unless you export a backup yourself.',

  // --- Statistics (MR-04 "Charts and history") ---------------------------------
  'statistics.title': 'Statistics',
  'statistics.completed': 'Completed',
  'statistics.dismissed': 'Dismissed',
  'statistics.missed': 'Missed',
  'statistics.snoozed': 'Snoozed',
  'statistics.mostActive': 'Most active reminder',
  'statistics.dailyBreakdown': 'Day by day',
  'statistics.empty.title': 'No history yet',
  'statistics.empty.body': 'Once reminders start alerting, a summary appears here.',
  // Translator note: {date}, {completed}, {dismissed} and {missed} are already formatted.
  'statistics.dayAccessible': '{date}: {completed} completed, {dismissed} dismissed, {missed} missed',

  // --- About ---------------------------------------------------------------------
  'about.title': 'About',
  'about.version': 'Version {version}',
  'about.schemaVersion': 'Database schema {version}',
  'about.contractVersion': 'Bridge contract {version}',
  'about.buildVariant': 'Build {variant}',
  'about.license': 'License',
  'about.licenseValue': 'Apache License 2.0',
  'about.sourceCode': 'Source code',
  'about.privacyDetails': 'Privacy details',
  'about.noInternet': 'This app has no Internet permission and makes no network requests.',
  'about.madeFor': 'Built for a calm, offline, local-first media reminder.',

  // --- Generic actions/states --------------------------------------------------
  'action.cancel': 'Cancel',
  'action.save': 'Save',
  'action.delete': 'Delete',
  'action.retry': 'Retry',
  'action.details': 'Details',
  'action.close': 'Close',
  'action.moreOptions': 'More options',
  'action.back': 'Back',
  'error.unexpected.title': 'Something went wrong',
  'error.unexpected.effect': 'The last action could not be completed.',
  'error.bridgeUnavailable.title': 'Native features are unavailable',
  'error.bridgeUnavailable.effect':
    'This build is running without the Android reliability core connected.',
  'error.updateRequired.title': 'Update required',
  'error.updateRequired.effect': 'This version of the app is out of date.',
  'loading.startingUp': 'Starting up',
  'loading.repairing': 'Finishing an earlier operation',
} as const;
