// Configure repositories globally for all projects and builds
allprojects {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

settingsEvaluated { settings ->
    settings.pluginManagement {
        repositories {
            google()
            mavenCentral()
            gradlePluginPortal()
        }
    }
}
