/**
 * ID and correlation-ID generation.
 *
 * Injected for the same reason as `ClockService`: deterministic tests, and one
 * place to change if the ID strategy ever changes. MR-08 requires UUIDs to be
 * lowercase canonical strings; correlation IDs share the same generator
 * because they have identical uniqueness requirements without the entity
 * semantics.
 *
 * MR-09: "Primary IDs are UUID strings generated by secure platform UUID" —
 * that rule governs Room *entity* IDs, generated in Kotlin. A JS-side
 * correlation ID is a diagnostic label, not a persisted identity key, so it
 * does not need a CSPRNG; Hermes has no Node `crypto` module to provide one
 * without adding a native polyfill package for this alone.
 */

const randomHex = (length: number): string =>
  Array.from({length}, () => Math.floor(Math.random() * 16).toString(16)).join('');

/** RFC 4122-shaped v4 UUID. Not cryptographically secure — see module comment. */
const pseudoUuidV4 = (): string =>
  `${randomHex(8)}-${randomHex(4)}-4${randomHex(3)}-${(8 + Math.floor(Math.random() * 4)).toString(16)}${randomHex(3)}-${randomHex(12)}`;

export interface IdGenerator {
  correlationId(): string;
}

export const createIdGenerator = (): IdGenerator => ({
  correlationId: () => pseudoUuidV4(),
});

/** Deterministic generator for tests: `test-correlation-1`, `-2`, ... */
export const createSequentialIdGenerator = (prefix = 'test-correlation'): IdGenerator => {
  let counter = 0;
  return {
    correlationId: () => `${prefix}-${(counter += 1)}`,
  };
};
