package com.aslam.mediareminder.data.db.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.PrimaryKey

/**
 * MR-09 `active_alarm_session`.
 *
 * More than one row can be `alerting` at once — the "multiple simultaneous
 * reminders" case (docs/decision-log.md): [com.aslam.mediareminder.alarm.AlarmDispatchReceiver]
 * still only ever claims one occurrence per dispatch (ADR-005's single
 * global alarm is unchanged), but a second reminder can become due, get
 * dispatched, and post its own session while the first is still unresolved.
 * [com.aslam.mediareminder.alarm.AlarmRingingService] is what enforces "at
 * most one *ringing*" — it queues every `alerting` session but only ever
 * plays sound/vibration and shows [com.aslam.mediareminder.alarm.AlarmActivity]
 * for the current one, promoting the next queued session when the current
 * one resolves.
 *

 * [actionNonce] is what makes [com.aslam.mediareminder.alarm.AlarmActionReceiver]'s
 * Play/Snooze/Dismiss idempotent and forgery-resistant (MR-08 "Alarm action
 * contract": "Action nonce is generated by native... code. A result may be
 * replayed for an identical nonce") — a notification action `Intent` that
 * does not carry the current nonce is rejected, not merely a duplicate.
 */
@Entity(
    tableName = "active_alarm_session",
    foreignKeys = [
        ForeignKey(
            entity = OccurrenceEntity::class,
            parentColumns = ["id"],
            childColumns = ["occurrence_id"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
)
data class ActiveAlarmSessionEntity(
    @PrimaryKey
    @ColumnInfo(name = "id")
    val id: String,

    @ColumnInfo(name = "occurrence_id")
    val occurrenceId: String,

    @ColumnInfo(name = "reminder_id")
    val reminderId: String,

    @ColumnInfo(name = "state")
    val state: String,

    @ColumnInfo(name = "started_at")
    val startedAt: Long,

    /** e.g. `"unlocked_notification"` — see `NotificationCoordinator`'s scope note for why there is only one value today. */
    @ColumnInfo(name = "presentation_decision")
    val presentationDecision: String,

    @ColumnInfo(name = "notification_id")
    val notificationId: Int,

    @ColumnInfo(name = "action_nonce")
    val actionNonce: String,

    @ColumnInfo(name = "last_update")
    val lastUpdate: Long,
) {
    companion object {
        const val STATE_ALERTING = "alerting"
        const val STATE_RESOLVED = "resolved"
    }
}
