"""Derive every Nudgio brand raster and launcher vector from the SVG master.

Two outputs, one source of truth (assets/brand/nudgio-mark.svg):

  web/brand/*.png                     the site's icons and OG image
  android/.../ic_launcher_*.xml       the adaptive launcher icon layers

The PNGs are drawn by sweeping circles along the master's own centrelines --
a round-capped stroke IS a circle swept along its path -- at 4x and
downsampled, so the raster is the master rather than a lookalike. The vector
drawables re-emit the master's path data verbatim. Keep PATH_* below in sync
with the SVG; everything else follows from them.

Run: python scripts/build-brand-assets.py
"""
from PIL import Image, ImageDraw
from xml.etree import ElementTree
import os

COBALT = (45, 77, 181)      # #2D4DB5
APRICOT = (233, 181, 142)   # #E9B58E
CREAM = (247, 244, 238)     # #F7F4EE
VIEW = (551, 512, 968)      # viewBox x, y, side

STEM = ((715, 788), (715, 1358), 242)
SHOULDER = (((718, 1350), (718, 1050), (720, 772), (1037, 772)),
            ((1037, 772), (1250, 772), (1241, 850), (1241, 1350)))
CHIMES = ((((1026, 536), (1120, 536), (1215, 560), (1259, 598)), 49),
          (((1412, 799), (1448, 860), (1456, 930), (1452, 998)), 49))
SPHERE = (1372, 671, 73)

# --- raster -----------------------------------------------------------------

def bez(p, t):
    mt = 1 - t
    return (mt**3*p[0][0] + 3*mt*mt*t*p[1][0] + 3*mt*t*t*p[2][0] + t**3*p[3][0],
            mt**3*p[0][1] + 3*mt*mt*t*p[1][1] + 3*mt*t*t*p[2][1] + t**3*p[3][1])

def sweep(draw, pts, width, scale, ox, oy, colour):
    r = width / 2 * scale
    for x, y in pts:
        cx, cy = (x - ox) * scale, (y - oy) * scale
        draw.ellipse([cx - r, cy - r, cx + r, cy + r], fill=colour)

def render(size, ss=4):
    n = size * ss
    scale = n / VIEW[2]
    ox, oy = VIEW[0], VIEW[1]
    img = Image.new("RGBA", (n, n), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    (x0, y0), (x1, y1), w = STEM
    sweep(d, [(x0, y0 + (y1 - y0) * i / 600) for i in range(601)], w, scale, ox, oy, COBALT + (255,))
    pts = [bez(SHOULDER[0], i / 800) for i in range(801)] + [bez(SHOULDER[1], i / 800) for i in range(801)]
    sweep(d, pts, 224, scale, ox, oy, COBALT + (255,))
    for curve, w in CHIMES:
        sweep(d, [bez(curve, i / 400) for i in range(401)], w, scale, ox, oy, COBALT + (255,))
    cx, cy, r = SPHERE
    cx, cy, r = (cx - ox) * scale, (cy - oy) * scale, r * scale
    d.ellipse([cx - r, cy - r, cx + r, cy + r], fill=APRICOT + (255,))
    return img.resize((size, size), Image.LANCZOS)

# --- android vector ---------------------------------------------------------

# The master's 968-unit mark box is placed on the central 54dp of the 108dp
# adaptive-icon canvas. A 1936-unit viewport makes one 968-unit box exactly
# half the canvas, so the only transform is a translate carrying the master's
# origin (551,512) to the 484-unit inset -- no scale factor, which is why
# every number emitted below still matches the SVG.
VIEWPORT = VIEW[2] * 2
INSET = (VIEWPORT - VIEW[2]) // 2
TRANSLATE = (INSET - VIEW[0], INSET - VIEW[1])   # (-67, -28)

KAPPA = 0.5522847498


def _cubic(p):
    return "C%s,%s %s,%s %s,%s" % (p[1][0], p[1][1], p[2][0], p[2][1], p[3][0], p[3][1])


def _num(v):
    return ("%.2f" % v).rstrip("0").rstrip(".")


def _strokes():
    """(pathData, strokeWidth, needsJoin) for every stroked path in the master."""
    (x0, y0), (x1, y1), w = STEM
    yield "M%s,%s L%s,%s" % (x0, y0, x1, y1), w, False
    yield ("M%s,%s %s %s" % (SHOULDER[0][0][0], SHOULDER[0][0][1],
                             _cubic(SHOULDER[0]), _cubic(SHOULDER[1])), 224, True)
    for curve, w in CHIMES:
        yield "M%s,%s %s" % (curve[0][0], curve[0][1], _cubic(curve)), w, False


def _sphere_path():
    """VectorDrawable has no <circle>; four cubics are exact to 0.02%."""
    cx, cy, r = SPHERE
    k = r * KAPPA
    pts = [
        (cx + r, cy), (cx + r, cy + k), (cx + k, cy + r), (cx, cy + r),
        (cx - k, cy + r), (cx - r, cy + k), (cx - r, cy),
        (cx - r, cy - k), (cx - k, cy - r), (cx, cy - r),
        (cx + k, cy - r), (cx + r, cy - k), (cx + r, cy),
    ]
    out = "M%s,%s" % (_num(pts[0][0]), _num(pts[0][1]))
    for i in range(1, 13, 3):
        out += " C" + " ".join("%s,%s" % (_num(p[0]), _num(p[1])) for p in pts[i:i + 3])
    return out + " Z"


HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by scripts/build-brand-assets.py from assets/brand/nudgio-mark.svg.
  Do not hand-edit: change the master, then re-run the script.

%s
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="%d"
    android:viewportHeight="%d">
    <group
        android:translateX="%d"
        android:translateY="%d">
"""

FOREGROUND_NOTE = """  The mark, in the brand's own colours. Until 2.1.1 this layer wrapped a
  1.5 MB JPEG: a second full-resolution copy of artwork the JS side already
  bundles, soft at every launcher size.

  The master's 968-unit mark box sits on the central 54dp of the 108dp
  canvas. That keeps the furthest ink (the stem's bottom-left round cap, 604
  units from centre) inside a 67dp circle, within the 72dp the launcher mask
  reveals.

  Note for future edits: a double hyphen cannot appear in an XML comment,
  so these notes use parentheses where prose would want a dash."""

MONOCHROME_NOTE = """  The themed-icon (Android 13+) variant: identical geometry, one colour,
  tinted by the system from the user's wallpaper. The sphere stays a
  separate shape rather than merging into the strokes, so the mark still
  reads as itself once the colour is gone."""


def _vector(note, mark_colour, accent_colour):
    out = HEADER % (note, VIEWPORT, VIEWPORT, TRANSLATE[0], TRANSLATE[1])
    for data, width, join in _strokes():
        out += '        <path\n            android:fillColor="#00000000"\n'
        out += '            android:pathData="%s"\n' % data
        out += '            android:strokeColor="%s"\n' % mark_colour
        out += '            android:strokeLineCap="round"\n'
        if join:
            out += '            android:strokeLineJoin="round"\n'
        out += '            android:strokeWidth="%d" />\n' % width
    out += '        <path\n            android:fillColor="%s"\n' % accent_colour
    out += '            android:pathData="%s" />\n' % _sphere_path()
    return out + "    </group>\n</vector>\n"


# --- web svg ----------------------------------------------------------------

WEB_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="%d %d %d %d" role="img" aria-label="Nudgio">
  <title>Nudgio</title>
  <!-- GENERATED by scripts/build-brand-assets.py from assets/brand/nudgio-mark.svg.
       Same geometry as the master, plus a prefers-color-scheme rule: this copy
       is the favicon, and a tab strip has its own light/dark that the page's
       theme control does not reach. -->
  <style>
    .mark { stroke: %s }
    .accent { fill: %s }
    @media (prefers-color-scheme: dark) {
      .mark { stroke: %s }
      .accent { fill: %s }
    }
  </style>
%s  <circle class="accent" cx="%d" cy="%d" r="%d" />
</svg>
"""

DARK_COBALT = "#BAC8FF"
DARK_APRICOT = "#F1BE98"


def _hex(rgb):
    return "#%02X%02X%02X" % rgb


def web_svg():
    body = ""
    for data, width, join in _strokes():
        join_attr = ' stroke-linejoin="round"' if join else ""
        body += ('  <path class="mark" fill="none" stroke-width="%d" '
                 'stroke-linecap="round"%s d="%s" />\n' % (width, join_attr, data))
    return WEB_SVG % (VIEW[0], VIEW[1], VIEW[2], VIEW[2],
                      _hex(COBALT), _hex(APRICOT), DARK_COBALT, DARK_APRICOT,
                      body, SPHERE[0], SPHERE[1], SPHERE[2])


# --- master agreement -------------------------------------------------------

def verify(master_path):
    """Fail loudly if the constants above have drifted from the SVG master.

    Everything this script emits is derived from those constants, so without
    this check "keep them in sync with the master" is only a hope. The master
    writes its path data comma-separated precisely so this can be exact.
    """
    with open(master_path, encoding="utf-8") as f:
        master = f.read()
    missing = []
    for data, width, _ in _strokes():
        if 'd="%s"' % data not in master:
            missing.append('path d="%s"' % data)
        if 'stroke-width="%d"' % width not in master:
            missing.append('stroke-width="%d"' % width)
    circle = 'cx="%d" cy="%d" r="%d"' % SPHERE
    if circle not in master:
        missing.append("circle " + circle)
    if 'viewBox="%d %d %d %d"' % (VIEW[0], VIEW[1], VIEW[2], VIEW[2]) not in master:
        missing.append("viewBox")
    if missing:
        raise SystemExit(
            "build-brand-assets: drifted from %s\n  missing: %s\n"
            "Fix the constants in this script or the master, then re-run."
            % (master_path, "\n           ".join(missing)))
    print("verified against assets/brand/nudgio-mark.svg")


root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
verify(os.path.join(root, "assets", "brand", "nudgio-mark.svg"))

out = os.path.join(root, "web", "brand")
os.makedirs(out, exist_ok=True)
for size in (512, 192, 64):
    render(size).save(os.path.join(out, "nudgio-mark-%d.png" % size), optimize=True)
    print("wrote web/brand/nudgio-mark-%d.png" % size)

og = Image.new("RGB", (1200, 630), CREAM)
m = render(300)
og.paste(m, (450, 165), m)
og.save(os.path.join(out, "nudgio-og.png"), optimize=True)
print("wrote web/brand/nudgio-og.png")

with open(os.path.join(out, "nudgio-mark.svg"), "w", newline="\n") as f:
    f.write(web_svg())
print("wrote web/brand/nudgio-mark.svg")

def write_xml(path, text):
    """Write only if it parses.

    aapt rejects malformed resource XML roughly 12 minutes into a release
    build, and the first thing it caught here was a double hyphen inside a
    comment -- which is exactly the kind of thing that is free to check now
    and expensive to find later.
    """
    try:
        ElementTree.fromstring(text)
    except ElementTree.ParseError as err:
        raise SystemExit("build-brand-assets: %s is not valid XML: %s" % (path, err))
    with open(path, "w", newline="\n", encoding="utf-8") as f:
        f.write(text)
    print("wrote", os.path.relpath(path, root).replace(os.sep, "/"))


drawable = os.path.join(root, "android", "app", "src", "main", "res", "drawable")
write_xml(os.path.join(drawable, "ic_launcher_foreground.xml"),
          _vector(FOREGROUND_NOTE, "@color/ic_launcher_mark", "@color/ic_launcher_accent"))
write_xml(os.path.join(drawable, "ic_launcher_monochrome.xml"),
          _vector(MONOCHROME_NOTE, "@color/ic_launcher_mono", "@color/ic_launcher_mono"))
